# Generated by Django 2.2.5 on 2019-09-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250)),
                ('Age', models.IntegerField(default=0)),
                ('Job_Position', models.CharField(max_length=250)),
            ],
        ),
    ]
