# Generated by Django 2.2.5 on 2019-09-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobrestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
