# Generated by Django 2.2.5 on 2019-09-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobrestapp', '0002_auto_20190923_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('Job_Description', models.TextField()),
            ],
        ),
    ]
