# Generated by Django 2.2.5 on 2019-09-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobrestapp', '0005_auto_20190923_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_job',
            name='applicants',
        ),
    ]
