# Generated by Django 2.2.5 on 2019-09-24 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobrestapp', '0006_remove_post_job_applicants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobrestapp.Applicant')),
                ('postjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobrestapp.Post_Job')),
            ],
        ),
        migrations.AddField(
            model_name='post_job',
            name='applicants',
            field=models.ManyToManyField(through='Jobrestapp.Applications', to='Jobrestapp.Applicant'),
        ),
    ]
