# Generated by Django 2.2.5 on 2019-09-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='Age',
            field=models.IntegerField(default=0),
        ),
    ]
